config/routes.rb
Rails.application.routes.draw do


  get 'clear_vision/index'
  get 'clear_vision/show'
  root to: "landingpage#show"


  resources :resume, only: [:index]
  post '/send_mail', to: 'sendmail#create'

  get '/credit_check',to: 'creditchecks#new'
  post '/credit_check', to: 'creditchecks#create'

  get '/jungle_beat', to: 'junglebeats#new'
  post '/jungle_beat', to: 'junglebeats#create'


  get '/night_writer', to: 'nightwriter#new'
  post '/night_writer', to: 'nightwriter#create'
  post '/night_reader', to: 'nightwriter#read'

  get '/magic_game', to: 'magic_game#new'
  get '/clear_vision', to: 'clear_vision#index'
  post '/images', to: 'clear_vision#create'

  resources :contact, only: [:index]
  resources :mystory, only: [:index]
  resources :projects, only: [:index, :show]
end

app/controllers/clear_vision_controller.rb
class ClearVisionController < ApplicationController
  def index
    @image = Image.new
  end

  def create
    if !params['image']
      redirect_to root_path, alert: "Please Choose a File and Try Again!!"
    else
      image = Image.create(image_params)
      url = "./public" + image.avatar.url.split("?").first
      this = ClearVisionService.new.get_text(url)
      render :show, :locals => {:pic => this.split("\n")}
      image.destroy
    end
  end

  def show
    
  end

  private
  def image_params
    params.require(:image).permit(:avatar)
  end
end

app/helpers/clear_vision_helper.rb
module ClearVisionHelper
end

app/views/clear_vision/index.html.erb
<!-- <link rel="stylesheet" href="/mystory/show.css" title="CSS" type="text/css"/>
<div class="container">
  <%= form_for @image do |form| %>
  <h2 class='linkedlist-description'>This Program is based on Luhn's algorithm, also known as the "modulus 10" or "mod 10" algorithm, named after IBM scientist Hans Peter Luhn, is a simple checksum formula used to validate a variety of identification numbers, such as credit card numbers, IMEI numbers, National Provider Identifier numbers in the United States<br><br>
    <%= form.file_field :avatar %>
    <%= form.submit "Covert Now"%>
  <% end %>
<div> -->

<link rel="stylesheet" href="/mystory/show.css" title="CSS" type="text/css"/>
<div class="container">
  <%= form_for @image do |form| %>
  <h2 class='linkedlist-description'>OCR (optical character recognition) is the use of technology to distinguish printed or handwritten text characters inside digital images of physical documents, such as a scanned paper document. The basic process of OCR involves examining the text of a document and translating the characters into code that can be used for data processing. OCR is sometimes also referred to as text recognition.<br>
    <br>This program uses google's Cloud Vision API. Also detects most common types of links!! Try one of your screenshots that has links you want to click on!!<br><br>
    <%= form.file_field :avatar %>
    <%= form.submit "Covert Now"%>
  <% end %>
</div>

app/views/clear_vision/show.html.erb
<link rel="stylesheet" href="/mystory/show.css" title="CSS" type="text/css"/>
<div class="container">
    <!-- <p class="result-check"> -->
    <h2 id='clear-vision-result'>
    <%pic.each do |p|%>
      <% p.split(" ").each do |t| %>
        <% if t.include?(".com") || t.include?(".mil") || t.include?(".us") || t.include?(".edu") || t.include?(".info") || t.include?(".io") || t.include?(".gov") || t.include?(".org") || t.include?(".net")%>
          <% if t.start_with?("https://")%>
            <%=link_to t, t, class: 'detected-link'%>
          <% else %>
            <%=link_to t, "http://" + t , class: 'detected-link'%>
          <% end %>
        <% elsif (t.length >= 10 && t.length <= 18 && t.count("a-zA-Z") == 0) %>
          <%=link_to t, "tel:" + t, class: 'detected-link'%>
        <% else %>
          <%= t %>
        <% end %>
      <% end %><br>
    <% end %></h2>
    <br>
    <br>
    <h4 class='link-to-new1'><%=link_to 'Try New One', clear_vision_path%>
</div>