config/routes.rb
Rails.application.routes.draw do


  get 'clear_vision/index'
  get 'clear_vision/show'
  root to: "landingpage#show"


  resources :resume, only: [:index]
  post '/send_mail', to: 'sendmail#create'

  get '/credit_check',to: 'creditchecks#new'
  post '/credit_check', to: 'creditchecks#create'

  get '/jungle_beat', to: 'junglebeats#new'
  post '/jungle_beat', to: 'junglebeats#create'


  get '/night_writer', to: 'nightwriter#new'
  post '/night_writer', to: 'nightwriter#create'
  post '/night_reader', to: 'nightwriter#read'

  get '/magic_game', to: 'magic_game#new'
  get '/clear_vision', to: 'clear_vision#index'
  post '/images', to: 'clear_vision#create'

  resources :contact, only: [:index]
  resources :mystory, only: [:index]
  resources :projects, only: [:index, :show]
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index

  end
end

app/views/contact/index.html.erb
<link rel="stylesheet" href="/mystory/show.css" title="CSS" type="text/css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="container">
  <%= form_tag send_mail_path do %>
  <%=label_tag :Name %>
  <%=text_field_tag :name %>

  <%=label_tag :Email %>
  <%=text_field_tag :email%>

  <%=label_tag :Message %>
  <%=text_area_tag :message%>

  <%=submit_tag :"Send Message"%>
  <%end%>
</div>

<div class='youcanalsoemail'>
  <center><h2>You can also contact me at:</h2>
  <h1>manojpanta95@gmail.com</h1></center>
</div>