config/routes.rb
Rails.application.routes.draw do


  get 'clear_vision/index'
  get 'clear_vision/show'
  root to: "landingpage#show"


  resources :resume, only: [:index]
  post '/send_mail', to: 'sendmail#create'

  get '/credit_check',to: 'creditchecks#new'
  post '/credit_check', to: 'creditchecks#create'

  get '/jungle_beat', to: 'junglebeats#new'
  post '/jungle_beat', to: 'junglebeats#create'


  get '/night_writer', to: 'nightwriter#new'
  post '/night_writer', to: 'nightwriter#create'
  post '/night_reader', to: 'nightwriter#read'

  get '/magic_game', to: 'magic_game#new'
  get '/clear_vision', to: 'clear_vision#index'
  post '/images', to: 'clear_vision#create'

  resources :contact, only: [:index]
  resources :mystory, only: [:index]
  resources :projects, only: [:index, :show]
end

app/models/night_writer.rb
class NightWriter
  attr_reader :dictionary,
              :braille_splitted_in_lines,
              :brailles_in_hash,
              :brailles
  def initialize
    @dictionary = { 'a' => '0.....',
                    'b' => '0.0...',
                    'c' => '00....',
                    'd' => '00.0..',
                    'e' => '0..0..',
                    'f' => '000...',
                    'g' => '0000..',
                    'h' => '0.00..',
                    'i' => '.00...',
                    'j' => '.000..',
                    'k' => '0...0.',
                    'l' => '0.0.0.',
                    'm' => '00..0.',
                    'n' => '00.00.',
                    'o' => '0..00.',
                    'p' => '000.0.',
                    'q' => '00000.',
                    'r' => '0.000.',
                    's' => '.00.0.',
                    't' => '.0000.',
                    'u' => '0...00',
                    'v' => '0.0.00',
                    'w' => '.000.0',
                    'x' => '00..00',
                    'y' => '00.000',
                    'z' => '0..000',
                    ' ' => '......',
                    '.' => '..00.0',
                    ',' => '..0...',
                    '!' => '..000.',
                    '?' => '..0.00',
                    "'" => '....0.',
                    '-' => '....00',
                    'cap' => '.....0',
                    "\n" => '000000',
                    "#" => '.0.000',
                    'numbers' => {'1' => '0.....',
                                  '2' => '0.0...',
                                  '3' => '00....',
                                  '4' => '00.0..',
                                  '5' => '0..0..',
                                  '6' => '000...',
                                  '7' => '0000..',
                                  '8' => '0.00..',
                                  '9' => '.00...',
                                  '0' => '.000..'}
                                }
    @brailles = ''
    @brailles_in_hash = {}
    @braille_splitted_in_lines = []
    @letters = ('A'..'Z')
  end

  def get_braille_string(letters)
    letters = letters.chars

    letters.map do |letter|
      if letter.upcase == letter && alphabets?(letter)
        @brailles << dictionary['cap']
        @brailles << dictionary[letter.downcase]
      elsif numbers?(letter)
        @brailles << dictionary['#']
        @brailles << dictionary['numbers'][letter]
      elsif letter == "\r"
      else
        @brailles << dictionary[letter]
      end
    end
    @brailles
  end

  def alphabets?(letter)
    @letters.include?(letter)
  end

  def numbers?(letter)
    ('0'..'9').include?(letter)
  end

  def splitting_into_brailles_in_hash
    count = 1
    until @brailles.empty?
      @brailles_in_hash[count] = brailles[0..239]
      @brailles.slice!(0..239)
      count += 1
    end
  end

  def into_rows(count = 1, top_row = '', middle_row = '', bottom_row = '')
    return @braille_splitted_in_lines if count > @brailles_in_hash.length

    until @brailles_in_hash[count].empty?
      top_row << @brailles_in_hash[count].slice!(0..1)
      middle_row << @brailles_in_hash[count].slice!(0..1)
      bottom_row << @brailles_in_hash[count].slice!(0..1)
    end
    rows = top_row + "newline" + middle_row + "newline" + bottom_row + "newline"
    @braille_splitted_in_lines << rows
    count += 1
    into_rows(count)
  end
end

app/controllers/nightwriter_controller.rb
class NightwriterController < ApplicationController

  def new
  end

  def create
    nw = NightWriter.new
    nw.get_braille_string(params[:answer])
    nw.splitting_into_brailles_in_hash
    nw.into_rows
    @translated = nw.braille_splitted_in_lines.map do |t|
      t.split('newline')
    end.flatten
    render :show
  end

  def read
    nightreader = NightReader.new(params[:answer1].split("\r\n"))
    nightreader.put_every_three_string_into_hash
    nightreader.create_braille_string
    nightreader.create_output_string
    @translated1 = nightreader.output_string
    render :show
  end

end

app/views/nightwriter/new.html.erb
<link rel="stylesheet" href="/mystory/show.css" title="CSS" type="text/css"/>
<div class="container">
  <%= form_tag night_writer_path do %>
    <h2 class='linkedlist-description'>This program translates English to Braille and Vice versa. 0 represents raised dots.Please limit your entry within: A-Z, a-z, 0-9, space, dot/period, comma, question mark, exclamation mark, dash, and new lines <br><br>
    <%=label_tag :"Enter English Here to Traslate to Braille"%>
    <%=text_area_tag :answer%>
    <%=submit_tag "Enter" %>
  <%end%>
  <br>
  <br>

  <%= form_tag night_reader_path do %>
    <%=label_tag :"Enter Braille Here to Traslate to English"%>
    <%=text_area_tag :answer1%>
    <%=submit_tag "Enter" %>
  <%end%>
</div>

app/views/nightwriter/show.html.erb
<link rel="stylesheet" href="/mystory/show.css" title="CSS" type="text/css"/>
<div class="container-braille">
  <%if @translated%>
    <div>
      <%@translated.each do |t|%>
      <article class = 'this-is-braille'><%=t%><br>
      <%end%>
    </div>
    <h4 class ='link-to-new'><%=link_to 'Try New One', night_writer_path%>

  <%else%>
    <div>
     <article class = 'this-is-braille'><%=@translated1%>
    </div>
    <h4 class ='link-to-new'><%=link_to 'Try New One', night_writer_path%>
  <%end%>
</div>